version: '3'

services:

  api:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    container_name: chat_app
    volumes:
      - .:/chat_app
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always

  postgres:
    platform: linux/amd64
    image: postgres:15.1-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=oiansheks@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=oianshek
    volumes:
      - ./pgadmin:/var/lib/pgadmin
