version: '3'

services:

  backend:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: chat_app
    volumes:
      - .:/chat_app
    ports:
      - "8001:8001"
    networks:
      - backend
    depends_on:
      - postgres

  postgres:
    platform: linux/amd64
    image: postgres:15.1-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - backend

  networks:
    backend:
      driver: bridge
